# Utiliser une image Nginx
FROM nginx:alpine


RUN rm /etc/nginx/conf.d/default.conf

COPY index.html /usr/share/nginx/html/index.html

RUN echo "server { listen 80; root /usr/share/nginx/html; \
      location / { try_files \$uri /index.html; }}" > /etc/nginx/conf.d/app.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]